project:
  type: book
  output-dir: docs

book:
  title: "friendly-probability-book"
  author: "Norah Jones"
  date: "9/26/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



